---
output: 
  html_document: 
    toc: false
    toc_depth: 1
    toc_float: true
    includes:
      in_header: header.html
      before_body: below.html
    css: style.css
lang: es-CO
---



<small><center>nndasndñaldnlsaandlandlandlaasndaldnalsdnasldnasdnaslde más de 3800 días de conflictos. Cada día es un rectángulo y  su color representa la frecuencia de conflictos: mientras más oscuros mayores disputas y mientras más claro, menores. Pase el mouse sobre cualquier día para conocer mayores detalles</center></small>
<br>


<small><center>nndasndñaldnlsaandlandlandlaasndaldnalsdnasldnasdnaslde más de 3800 días de conflictos. Cada día es un rectángulo y  su color representa la frecuencia de conflictos: mientras más oscuros mayores disputas y mientras más claro, menores. Pase el mouse sobre cualquier día para conocer mayores detalles</center></small>
<br>

<small><center>nndasndñaldnlsaandlandlandlaasndaldnalsdnasldnasdnaslde más de 3800 días de conflictos. Cada día es un rectángulo y  su color representa la frecuencia de conflictos: mientras más oscuros mayores disputas y mientras más claro, menores. Pase el mouse sobre cualquier día para conocer mayores detalles</center></small>
<br>

<small><center>nndasndñaldnlsaandlandlandlaasndaldnalsdnasldnasdnaslde más de 3800 días de conflictos. Cada día es un rectángulo y  su color representa la frecuencia de conflictos: mientras más oscuros mayores disputas y mientras más claro, menores. Pase el mouse sobre cualquier día para conocer mayores detalles</center></small>
<br>

<small><center>nndasndñaldnlsaandlandlandlaasndaldnalsdnasldnasdnaslde más de 3800 días de conflictos. Cada día es un rectángulo y  su color representa la frecuencia de conflictos: mientras más oscuros mayores disputas y mientras más claro, menores. Pase el mouse sobre cualquier día para conocer mayores detalles</center></small>
<br>

<small><center>nndasndñaldnlsaandlandlandlaasndaldnalsdnasldnasdnaslde más de 3800 días de conflictos. Cada día es un rectángulo y  su color representa la frecuencia de conflictos: mientras más oscuros mayores disputas y mientras más claro, menores. Pase el mouse sobre cualquier día para conocer mayores detalles</center></small>
<br>